name: Code checks
on:
  - push
  - pull_request
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: npm i
      - run: ./node_modules/.bin/tsc --skipLibCheck --noEmit
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm run format:check
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm run build
